---
- name: install inginx
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Rehhat"

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Ensure Nginx is running
      wait_for:
        port: 8081
        delay: 10
        timeout: 30