---
- name: install linux apache
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family != "Windows"

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Ensure Apache is running
      wait_for:
        port: 80
        delay: 10
        timeout: 30